In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('glassdoor_data_eda.csv')

In [3]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Size', 'Founded', 'Type of ownership',
       'Industry', 'Sector', 'Revenue', 'hourly_salary', 'min_salary',
       'max_salary', 'avg_salary', 'job_type', 'seniority',
       'cleaned_description', 'sas_flag', 'xgboost_flag', 'scikit_flag',
       'pandas_flag', 'aws_flag', 'redshift_flag', 'apache_flag', 'spark_flag',
       'hadoop_flag', 'numpy_flag', 'scipy_flag', 'pyspark_flag', 'linux_flag',
       'jupyter_flag', 'sql_flag', 'cloud_flag', 'python_flag', 'phd_flag',
       'tableau_flag', 'len_description', 'state', 'city'],
      dtype='object')

In [4]:
# Dropping Unnecessary columns
df.drop(['Job Title', 'Salary Estimate', 'Job Description', 'Company Name', 'Location', 'Founded', 'hourly_salary', \
         'min_salary', 'max_salary', 'cleaned_description', 'len_description'], axis=1, inplace=True)

In [5]:
# Dropping rows with null numeric column
df = df.dropna(subset=['Rating'])

In [6]:
# Encoding categorical variables
df = pd.get_dummies(df)

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [8]:
X = df.drop('avg_salary', axis=1)
y = df['avg_salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print('Train size:', X_train.shape, '\nTest size:', X_test.shape  )

Train size: (392, 386) 
Test size: (98, 386)


In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
lr = LinearRegression()
lr.fit(X_train, y_train)
cross_val_score(lr, X_train, y_train, cv=3, scoring='neg_mean_absolute_error')

array([-3.37555646e+14, -1.50954975e+14, -1.10413517e+14])

In [11]:
from sklearn.tree import DecisionTreeRegressor
dtree = DecisionTreeRegressor()
dtree.fit(X_train, y_train)
cross_val_score(dtree, X_train, y_train, cv=3, scoring='neg_mean_absolute_error')

array([-25.48473282, -23.8778626 , -21.08461538])

In [12]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
cross_val_score(rf, X_train, y_train, cv=3, scoring='neg_mean_absolute_error')

array([-19.15396183, -18.99148855, -18.02747179])